name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        npm install

    - name: Build
      run: |
        npm run build
      env:
        REACT_APP_TEST_URL: ${{ secrets.REACT_APP_TEST_URL }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
